import { prisma } from './db'

// Common 5-letter words for secret words (curated list)
const SECRET_WORDS = [
  'about', 'above', 'abuse', 'actor', 'acute', 'admit', 'adopt', 'adult', 'after', 'again',
  'agent', 'agree', 'ahead', 'alarm', 'album', 'alert', 'alien', 'align', 'alike', 'alive',
  'allow', 'alone', 'along', 'alter', 'among', 'anger', 'angle', 'angry', 'apart', 'apple',
  'apply', 'arena', 'argue', 'arise', 'array', 'aside', 'asset', 'avoid', 'awake', 'award',
  'aware', 'badly', 'baker', 'bases', 'basic', 'beach', 'began', 'begin', 'being', 'below',
  'bench', 'billy', 'birth', 'black', 'blame', 'blind', 'block', 'blood', 'board', 'boost',
  'booth', 'bound', 'brain', 'brand', 'brass', 'brave', 'bread', 'break', 'breed', 'brief',
  'bring', 'broad', 'broke', 'brown', 'build', 'built', 'buyer', 'cable', 'calif', 'carry',
  'catch', 'cause', 'chain', 'chair', 'chaos', 'charm', 'chart', 'chase', 'cheap', 'check',
  'chess', 'chest', 'chief', 'child', 'china', 'chose', 'civil', 'claim', 'class', 'clean',
  'clear', 'click', 'climb', 'clock', 'close', 'cloud', 'coach', 'coast', 'could', 'count',
  'court', 'cover', 'craft', 'crash', 'crazy', 'cream', 'crime', 'cross', 'crowd', 'crown',
  'crude', 'curve', 'cycle', 'daily', 'dance', 'dated', 'dealt', 'death', 'debut', 'delay',
  'depth', 'doing', 'doubt', 'dozen', 'draft', 'drama', 'drank', 'dream', 'dress', 'drill',
  'drink', 'drive', 'drove', 'dying', 'eager', 'early', 'earth', 'eight', 'elite', 'empty',
  'enemy', 'enjoy', 'enter', 'entry', 'equal', 'error', 'event', 'every', 'exact', 'exist',
  'extra', 'faith', 'false', 'fault', 'fiber', 'field', 'fifth', 'fifty', 'fight', 'final',
  'first', 'fixed', 'flash', 'fleet', 'floor', 'fluid', 'focus', 'force', 'forth', 'forty',
  'forum', 'found', 'frame', 'frank', 'fraud', 'fresh', 'front', 'fruit', 'fully', 'funny',
  'giant', 'given', 'glass', 'globe', 'going', 'grace', 'grade', 'grand', 'grant', 'grass',
  'grave', 'great', 'green', 'gross', 'group', 'grown', 'guard', 'guess', 'guest', 'guide',
  'happy', 'harry', 'heart', 'heavy', 'hence', 'henry', 'horse', 'hotel', 'house', 'human',
  'ideal', 'image', 'index', 'inner', 'input', 'issue', 'japan', 'jimmy', 'joint', 'jones',
  'judge', 'known', 'label', 'large', 'laser', 'later', 'laugh', 'layer', 'learn', 'lease',
  'least', 'leave', 'legal', 'level', 'lewis', 'light', 'limit', 'links', 'lives', 'local',
  'loose', 'lower', 'lucky', 'lunch', 'lying', 'magic', 'major', 'maker', 'march', 'maria',
  'match', 'maybe', 'mayor', 'meant', 'media', 'metal', 'might', 'minor', 'minus', 'mixed',
  'model', 'money', 'month', 'moral', 'motor', 'mount', 'mouse', 'mouth', 'moved', 'movie',
  'music', 'needs', 'never', 'newly', 'night', 'noise', 'north', 'noted', 'novel', 'nurse',
  'occur', 'ocean', 'offer', 'often', 'order', 'other', 'ought', 'paint', 'panel', 'paper',
  'party', 'peace', 'peter', 'phase', 'phone', 'photo', 'piano', 'piece', 'pilot', 'pitch',
  'place', 'plain', 'plane', 'plant', 'plate', 'point', 'pound', 'power', 'press', 'price',
  'pride', 'prime', 'print', 'prior', 'prize', 'proof', 'proud', 'prove', 'queen', 'quick',
  'quiet', 'quite', 'radio', 'raise', 'range', 'rapid', 'ratio', 'reach', 'ready', 'refer',
  'right', 'rival', 'river', 'robin', 'roger', 'roman', 'rough', 'round', 'route', 'royal',
  'rural', 'scale', 'scene', 'scope', 'score', 'sense', 'serve', 'seven', 'shall', 'shape',
  'share', 'sharp', 'sheet', 'shelf', 'shell', 'shift', 'shine', 'shirt', 'shock', 'shoot',
  'short', 'shown', 'sight', 'simon', 'sixth', 'sixty', 'sized', 'skill', 'sleep', 'slide',
  'small', 'smart', 'smile', 'smith', 'smoke', 'solid', 'solve', 'sorry', 'sound', 'south',
  'space', 'spare', 'speak', 'speed', 'spend', 'spent', 'split', 'spoke', 'sport', 'staff',
  'stage', 'stake', 'stand', 'start', 'state', 'steam', 'steel', 'steep', 'steer', 'steve',
  'stick', 'still', 'stock', 'stone', 'stood', 'store', 'storm', 'story', 'strip', 'stuck',
  'study', 'stuff', 'style', 'sugar', 'suite', 'super', 'sweet', 'table', 'taken', 'taste',
  'taxes', 'teach', 'teeth', 'terry', 'texas', 'thank', 'theft', 'their', 'there', 'these',
  'thick', 'thing', 'think', 'third', 'those', 'three', 'threw', 'throw', 'thumb', 'tiger',
  'tight', 'timer', 'title', 'today', 'topic', 'total', 'touch', 'tough', 'tower', 'track',
  'trade', 'train', 'treat', 'trend', 'trial', 'tribe', 'trick', 'tried', 'tries', 'truck',
  'truly', 'trunk', 'trust', 'truth', 'twice', 'under', 'undue', 'union', 'unity', 'until',
  'upper', 'urban', 'usage', 'usual', 'valid', 'value', 'video', 'virus', 'visit', 'vital',
  'vocal', 'voice', 'waste', 'watch', 'water', 'wheel', 'where', 'which', 'while', 'white',
  'whole', 'whose', 'woman', 'women', 'world', 'worry', 'worse', 'worst', 'worth', 'would',
  'write', 'wrong', 'wrote', 'young', 'youth'
]

// Comprehensive dictionary of valid 5-letter words
const DICTIONARY_WORDS = [
  // Include all secret words
  ...SECRET_WORDS,
  // Additional valid words
  'aback', 'abase', 'abate', 'abbey', 'abbot', 'abide', 'abled', 'abode', 'abort', 'abound',
  'abrax', 'abuzz', 'abyss', 'acorn', 'acted', 'acrid', 'added', 'adept', 'admin', 'adobe',
  'afoot', 'afore', 'agate', 'agave', 'agile', 'aging', 'aglow', 'agony', 'aider', 'aided',
  'ailed', 'aimed', 'airer', 'aisle', 'alarm', 'album', 'alder', 'algae', 'alibi', 'alien',
  'align', 'alike', 'alive', 'allay', 'alley', 'alloy', 'aloft', 'alone', 'along', 'aloof',
  'aloud', 'alpha', 'altar', 'alter', 'amber', 'amble', 'amend', 'amino', 'amiss', 'among',
  'ample', 'amuse', 'angel', 'anger', 'angle', 'angry', 'anime', 'ankle', 'annex', 'annoy',
  'antic', 'apart', 'aphid', 'aping', 'apnea', 'apple', 'apply', 'apron', 'arbor', 'argue',
  'arise', 'armed', 'armor', 'aroma', 'arose', 'array', 'arrow', 'arson', 'artsy', 'ascot',
  'ashen', 'aside', 'askew', 'assay', 'asset', 'atoll', 'atone', 'attic', 'audio', 'audit',
  'augur', 'aunty', 'avail', 'avert', 'avoid', 'await', 'awake', 'award', 'aware', 'awash',
  'awful', 'awoke', 'axial', 'axiom', 'axion', 'azure', 'bacon', 'badge', 'badly', 'bagel',
  'baggy', 'baker', 'baler', 'balky', 'balmy', 'banal', 'banjo', 'barge', 'baron', 'basal',
  'based', 'baser', 'basic', 'basil', 'basin', 'basis', 'baste', 'batch', 'bathe', 'baton',
  'batty', 'baulk', 'bawdy', 'bayou', 'beach', 'beady', 'beard', 'beast', 'beech', 'beefy',
  'began', 'begot', 'being', 'belch', 'belly', 'below', 'bench', 'beret', 'berry', 'berth',
  'beset', 'betty', 'bevel', 'bicep', 'biddy', 'biden', 'bidet', 'bigot', 'bilge', 'billy',
  'binge', 'bingo', 'biome', 'birch', 'birth', 'bison', 'bitty', 'black', 'blade', 'blame',
  'bland', 'blank', 'blare', 'blast', 'blaze', 'bleak', 'bleat', 'bleed', 'bleep', 'blend',
  'bless', 'blimp', 'blind', 'blink', 'bliss', 'blitz', 'bloat', 'block', 'bloke', 'blond',
  'blood', 'bloom', 'blown', 'blues', 'bluff', 'blunt', 'blurb', 'blurt', 'blush', 'board',
  'boast', 'bobby', 'boded', 'bogan', 'bogey', 'bogie', 'boils', 'boing', 'boink', 'bolus',
  'bombe', 'bonds', 'boned', 'boner', 'bones', 'bongo', 'bonny', 'bonus', 'boobs', 'booby',
  'booed', 'booer', 'books', 'booms', 'boomy', 'boons', 'boors', 'boost', 'booth', 'boots',
  'booty', 'booze', 'boozy', 'borax', 'bored', 'borer', 'boric', 'borne', 'bosom', 'bossy',
  'botch', 'bough', 'boule', 'bound', 'bower', 'bowls', 'boxed', 'boxer', 'boxes', 'brace',
  'braid', 'brain', 'brake', 'brand', 'brash', 'brass', 'brave', 'bravo', 'brawl', 'brawn',
  'bread', 'break', 'breed', 'brews', 'briar', 'bribe', 'brick', 'bride', 'brief', 'brine',
  'bring', 'brink', 'briny', 'brisk', 'broad', 'broil', 'broke', 'brood', 'brook', 'broom',
  'broth', 'brown', 'brunt', 'brush', 'brute', 'buddy', 'budge', 'buffy', 'buggy', 'bugle',
  'build', 'built', 'bulge', 'bulky', 'bully', 'bumps', 'bumpy', 'bunch', 'bunny', 'burly',
  'burnt', 'burst', 'buses', 'bushy', 'buzzy', 'buyer', 'bylaw', 'cabal', 'cabby', 'cabin',
  'cable', 'cache', 'cacti', 'caddy', 'cadet', 'cagey', 'cairn', 'cakey', 'camel', 'cameo',
  'canal', 'candy', 'canny', 'canoe', 'canon', 'caper', 'caput', 'carat', 'carbon', 'cards',
  'cared', 'carer', 'cares', 'cargo', 'carny', 'carol', 'carry', 'carve', 'casio', 'caste',
  'catch', 'cater', 'cause', 'cavey', 'cease', 'cedar', 'cello', 'cells', 'chain', 'chair',
  'chalk', 'champ', 'chant', 'chaos', 'chaps', 'chard', 'charm', 'chart', 'chase', 'chasm',
  'cheap', 'cheat', 'check', 'cheek', 'cheer', 'chess', 'chest', 'chewy', 'chief', 'child',
  'chill', 'chimp', 'china', 'chirp', 'chive', 'chock', 'choir', 'choke', 'chomp', 'chord',
  'chore', 'chose', 'chowk', 'chuck', 'chump', 'chunk', 'churn', 'chute', 'cider', 'cigar',
  'cinch', 'circa', 'cited', 'civic', 'civil', 'clack', 'clad', 'claim', 'clamp', 'clang',
  'clank', 'clash', 'clasp', 'class', 'clean', 'clear', 'cleat', 'cleft', 'clerk', 'click',
  'cliff', 'climb', 'cling', 'clink', 'cloak', 'clock', 'clog', 'clone', 'close', 'cloth',
  'cloud', 'clout', 'clove', 'clown', 'clubs', 'cluck', 'clued', 'clues', 'clump', 'clung',
  'clunk', 'coach', 'coals', 'coast', 'coax', 'cobra', 'cocoa', 'coded', 'coder', 'codes',
  'coin', 'coke', 'cold', 'color', 'comet', 'comic', 'comma', 'coral', 'cord', 'corn',
  'couch', 'cough', 'could', 'count', 'court', 'cover', 'craft', 'cramp', 'crane', 'crank',
  'crash', 'crass', 'crate', 'crave', 'crawl', 'craze', 'crazy', 'creak', 'cream', 'creed',
  'creek', 'creep', 'creme', 'crepe', 'cress', 'crest', 'crick', 'cried', 'crier', 'cries',
  'crime', 'crimp', 'crisp', 'croak', 'crock', 'croft', 'crone', 'crony', 'crook', 'cross',
  'croup', 'crowd', 'crown', 'crude', 'cruel', 'crumb', 'crump', 'crunk', 'crush', 'crust',
  'crypt', 'cubic', 'cubit', 'cuckoo', 'cumin', 'curly', 'curry', 'curse', 'curve', 'curvy',
  'cushy', 'cutie', 'cyber', 'cycle', 'cynic', 'daddy', 'daily', 'daisy', 'dally', 'dance',
  'dandy', 'dared', 'dares', 'dated', 'dater', 'dates', 'datum', 'daunt', 'dawns', 'dealt',
  'death', 'debit', 'debug', 'debut', 'decaf', 'decay', 'decor', 'decoy', 'decry', 'defer',
  'deify', 'deity', 'delay', 'delta', 'delve', 'demon', 'demur', 'denim', 'dense', 'depot',
  'depth', 'derby', 'deter', 'detox', 'deuce', 'devil', 'diary', 'dicey', 'digit', 'dimly',
  'diner', 'dingo', 'dingy', 'diode', 'dirge', 'dirty', 'disco', 'ditch', 'ditto', 'ditty',
  'diver', 'dizzy', 'dodge', 'dodgy', 'doing', 'dolly', 'donor', 'donut', 'dopey', 'dorky',
  'dotty', 'doubt', 'dough', 'douse', 'dowdy', 'dowel', 'downs', 'downy', 'dowry', 'dozen',
  'draft', 'drain', 'drake', 'drama', 'drank', 'drape', 'drawl', 'drawn', 'dread', 'dream',
  'drear', 'dress', 'dried', 'drier', 'dries', 'drift', 'drill', 'drily', 'drink', 'drips',
  'drive', 'droit', 'droll', 'drone', 'drool', 'droop', 'dross', 'drove', 'drown', 'drubs',
  'drugs', 'drums', 'drunk', 'drupe', 'dryly', 'ducks', 'ducky', 'dummy', 'dumps', 'dumpy',
  'dunce', 'dunes', 'dunks', 'dusky', 'dusty', 'dutch', 'duvet', 'dwarf', 'dwell', 'dying',
  'dykes', 'eager', 'eagle', 'early', 'earth', 'easel', 'eaten', 'eater', 'eaves', 'ebbed',
  'ebony', 'ebook', 'eclat', 'edema', 'edged', 'edges', 'edict', 'edify', 'eerie', 'eight',
  'eject', 'eking', 'elbow', 'elder', 'elect', 'elegy', 'elfin', 'elide', 'elite', 'elope',
  'elude', 'elves', 'email', 'embed', 'ember', 'emcee', 'empty', 'enact', 'endow', 'enema',
  'enemy', 'enjoy', 'ennui', 'ensue', 'enter', 'entry', 'envoy', 'epoch', 'epoxy', 'equal',
  'equip', 'erase', 'erect', 'ergot', 'error', 'erupt', 'essay', 'ester', 'estop', 'ether',
  'ethic', 'ethos', 'etude', 'evade', 'event', 'every', 'evict', 'evils', 'evoke', 'exact',
  'exalt', 'excel', 'exert', 'exile', 'exist', 'expat', 'expel', 'exult', 'exude', 'fable',
  'faced', 'faces', 'facet', 'fad', 'faded', 'fades', 'fagot', 'fails', 'faint', 'fairy',
  'faith', 'fake', 'fakir', 'falls', 'false', 'fame', 'fancy', 'fangs', 'farce', 'farms',
  'fatal', 'fatso', 'fatty', 'faugh', 'fault', 'fauna', 'favors', 'fawn', 'faxed', 'faxes',
  'fazed', 'fears', 'feast', 'feats', 'feces', 'feeds', 'feels', 'feign', 'feint', 'fella',
  'fells', 'felon', 'fence', 'feral', 'ferry', 'fetch', 'fetid', 'fetus', 'feuds', 'fever',
  'fewer', 'fiber', 'fibre', 'ficus', 'fidel', 'field', 'fiend', 'fiery', 'fifes', 'fifth',
  'fifty', 'fight', 'figs', 'filed', 'files', 'fills', 'films', 'filmy', 'filth', 'final',
  'finds', 'fined', 'finer', 'fines', 'fired', 'fires', 'firms', 'first', 'fishy', 'fists',
  'fitly', 'fits', 'fiver', 'fives', 'fixed', 'fixer', 'fixes', 'fizzy', 'fjord', 'flack',
  'flags', 'flail', 'flair', 'flak', 'flame', 'flams', 'flank', 'flaps', 'flare', 'flash',
  'flask', 'flats', 'flaws', 'flax', 'fleas', 'fleck', 'flees', 'flesh', 'flex', 'flick',
  'flies', 'fling', 'flint', 'flips', 'flirt', 'float', 'flock', 'flood', 'floor', 'flops',
  'flora', 'floss', 'flour', 'flout', 'flows', 'flubs', 'fluff', 'fluid', 'fluke', 'flung',
  'flunk', 'flush', 'flute', 'flyby', 'flyer', 'foals', 'foams', 'focal', 'focus', 'folks',
  'fonts', 'foods', 'fools', 'foots', 'foray', 'force', 'fords', 'forge', 'forgo', 'forks',
  'forms', 'forte', 'forth', 'forty', 'forum', 'foul', 'found', 'fours', 'fowls', 'foxes',
  'foyer', 'frail', 'frame', 'frank', 'fraud', 'frays', 'freak', 'freed', 'frees', 'fresh',
  'friar', 'fried', 'fries', 'frill', 'frisk', 'fritz', 'frizz', 'frock', 'frogs', 'frond',
  'front', 'frost', 'frown', 'froze', 'fruit', 'fucks', 'fudge', 'fuels', 'fugue', 'fully',
  'fumes', 'funds', 'fungi', 'funks', 'funky', 'funny', 'furry', 'fused', 'fuses', 'fussy',
  'fuzzy', 'gabby', 'gaily', 'gains', 'gaits', 'gales', 'galls', 'games', 'gamma', 'gangs',
  'gapes', 'garb', 'gases', 'gates', 'gator', 'gaudy', 'gauge', 'gaunt', 'gauze', 'gavel',
  'gawky', 'gayly', 'gaze', 'gears', 'gecko', 'geeks', 'geeky', 'geese', 'gels', 'gems',
  'genes', 'genie', 'genre', 'gents', 'genus', 'germs', 'ghost', 'giant', 'gifts', 'gills',
  'gilt', 'gimpy', 'girds', 'girls', 'girly', 'girth', 'gists', 'given', 'giver', 'gives',
  'gizmo', 'glade', 'gland', 'glare', 'glass', 'glaze', 'gleam', 'glean', 'glide', 'glint',
  'globe', 'gloom', 'glory', 'gloss', 'glove', 'glows', 'glued', 'glues', 'glyph', 'gnarl',
  'gnash', 'gnats', 'gnaws', 'gnome', 'goads', 'goals', 'goats', 'godly', 'going', 'golds',
  'golfs', 'gone', 'gongs', 'gonna', 'goods', 'goody', 'gooey', 'goofy', 'goose', 'gores',
  'gorge', 'gotta', 'gouge', 'gourd', 'gowns', 'grabs', 'grace', 'grade', 'grads', 'graft',
  'grail', 'grain', 'grand', 'grant', 'grape', 'graph', 'grasp', 'grass', 'grate', 'grave',
  'gravy', 'grays', 'graze', 'great', 'greed', 'greek', 'green', 'greet', 'greys', 'grid',
  'grief', 'grill', 'grime', 'grimy', 'grind', 'grins', 'grips', 'grit', 'groan', 'groin',
  'groom', 'grope', 'gross', 'group', 'grout', 'grove', 'growl', 'grows', 'gruel', 'gruff',
  'grunt', 'guard', 'guava', 'guess', 'guest', 'guide', 'guild', 'guilt', 'guise', 'gulch',
  'gulfs', 'gulls', 'gully', 'gulps', 'gumbo', 'gummy', 'gunks', 'gunky', 'guppy', 'gurus',
  'gusto', 'gusts', 'gusty', 'gutsy', 'guys', 'gybes', 'gyoza', 'habit', 'hacks', 'hadnt',
  'haiku', 'hails', 'hairs', 'hairy', 'hajj', 'hales', 'halfs', 'halls', 'halos', 'halts',
  'halve', 'hams', 'hands', 'handy', 'hangs', 'hanks', 'happy', 'hardy', 'hared', 'hares',
  'harms', 'harps', 'harry', 'harsh', 'haste', 'hasty', 'hatch', 'hated', 'hater', 'hates',
  'hauls', 'haunt', 'haute', 'haven', 'havoc', 'hawks', 'hazed', 'hazel', 'hazer', 'hazes',
  'heads', 'heady', 'heals', 'heaps', 'heard', 'hears', 'heart', 'heats', 'heavy', 'hedge',
  'heeds', 'heels', 'hefty', 'heirs', 'heist', 'hello', 'helps', 'hence', 'henry', 'herbs',
  'herby', 'herds', 'heres', 'hertz', 'hests', 'hexed', 'hexes', 'hicks', 'hides', 'highs',
  'hiked', 'hiker', 'hikes', 'hills', 'hilly', 'hilts', 'hinds', 'hindi', 'hints', 'hippo',
  'hippy', 'hired', 'hires', 'hitch', 'hived', 'hives', 'hoagy', 'hoard', 'hoary', 'hobby',
  'hocks', 'hogan', 'hoist', 'holds', 'holes', 'holly', 'holms', 'holts', 'homes', 'homey',
  'honda', 'honed', 'hones', 'honey', 'honks', 'honor', 'hoods', 'hooey', 'hoofs', 'hooks',
  'hooky', 'hoops', 'hoots', 'hoped', 'hopes', 'horde', 'horns', 'horny', 'horse', 'hosts',
  'hotel', 'hound', 'hours', 'house', 'hovel', 'hover', 'howdy', 'howls', 'hubby', 'hubs',
  'huffs', 'huffy', 'hulks', 'hulky', 'hulls', 'human', 'humid', 'humor', 'humps', 'humus',
  'hunch', 'hunks', 'hunky', 'hunts', 'hurls', 'hurry', 'hurts', 'husks', 'husky', 'hussy',
  'hutch', 'hydra', 'hyena', 'hymen', 'hymns', 'hyped', 'hyper', 'hypos', 'ichor', 'icing',
  'icons', 'ideal', 'ideas', 'idiom', 'idiot', 'idled', 'idler', 'idles', 'idols', 'igloo',
  'ileum', 'image', 'imago', 'imbue', 'impel', 'inane', 'incur', 'index', 'indie', 'inept',
  'inert', 'infer', 'infix', 'infra', 'inked', 'inlay', 'inlet', 'inner', 'input', 'inset',
  'inter', 'intro', 'ionic', 'irade', 'irate', 'irids', 'irked', 'irons', 'islet', 'issue',
  'itchy', 'items', 'ivory', 'jaded', 'jades', 'jails', 'jams', 'japan', 'japes', 'jaws',
  'jazzy', 'jeans', 'jeers', 'jelly', 'jerks', 'jerky', 'jests', 'jesus', 'jetty', 'jewel',
  'jiffy', 'jihad', 'jimmy', 'jinks', 'jived', 'jives', 'jobs', 'jocks', 'johns', 'joins',
  'joint', 'jokes', 'jolly', 'jolts', 'jones', 'joust', 'jowls', 'joyed', 'judge', 'juice',
  'juicy', 'julep', 'jumbo', 'jumps', 'jumpy', 'junco', 'junks', 'junky', 'jurat', 'juror',
  'jurat', 'kadis', 'kapok', 'karma', 'kayak', 'kebab', 'kecks', 'keels', 'keeps', 'kelps',
  'kemps', 'kendo', 'kerbs', 'kern', 'ketch', 'keyed', 'keys', 'khaki', 'kicks', 'kiddo',
  'kills', 'kilns', 'kilos', 'kilts', 'kinds', 'kings', 'kinks', 'kinky', 'kiosk', 'kitty',
  'kiwis', 'klick', 'klutz', 'knack', 'knave', 'knead', 'kneel', 'knelt', 'knife', 'knish',
  'knits', 'knobs', 'knock', 'knoll', 'knots', 'known', 'knows', 'knurl', 'koala', 'kooky',
  'kraut', 'krill', 'label', 'labor', 'laced', 'laces', 'lacks', 'lacy', 'laded', 'laden',
  'lades', 'ladle', 'lady', 'lager', 'laird', 'lairs', 'lakes', 'lambs', 'lamed', 'lamer',
  'lames', 'lamps', 'lance', 'lands', 'lanes', 'lanky', 'lapel', 'lapse', 'larch', 'lards',
  'large', 'larks', 'larva', 'laser', 'lasso', 'lasts', 'latch', 'later', 'latex', 'lathe',
  'laths', 'laude', 'laugh', 'laura', 'lavas', 'lawns', 'laxly', 'layer', 'layup', 'lazed',
  'lazes', 'leads', 'leafy', 'leaks', 'leaky', 'leans', 'leant', 'leaps', 'learn', 'lease',
  'least', 'leave', 'ledge', 'leech', 'leeks', 'leers', 'lefts', 'legal', 'leggy', 'lemma',
  'lemon', 'lemur', 'lends', 'leper', 'letup', 'level', 'lever', 'lewis', 'liar', 'libel',
  'libre', 'liced', 'licks', 'lids', 'liege', 'liens', 'lieu', 'lifes', 'lift', 'light',
  'liked', 'liken', 'likes', 'lilac', 'limbo', 'limbs', 'limed', 'limes', 'limit', 'limns',
  'limp', 'lined', 'linen', 'liner', 'lines', 'links', 'lints', 'lions', 'lipse', 'lists',
  'liter', 'lithe', 'lived', 'liven', 'liver', 'lives', 'llama', 'loads', 'loaf', 'loams',
  'loamy', 'loans', 'loath', 'lobby', 'lobed', 'lobes', 'local', 'locks', 'lodge', 'lofty',
  'logic', 'login', 'logos', 'loins', 'lolly', 'loner', 'longs', 'looby', 'looks', 'looms',
  'loons', 'loony', 'loops', 'loopy', 'loose', 'loots', 'loped', 'loper', 'lopes', 'lords',
  'lored', 'lores', 'loser', 'loses', 'lossy', 'lotus', 'lough', 'loupe', 'lours', 'louse',
  'lousy', 'louts', 'loved', 'lover', 'loves', 'lowed', 'lower', 'lowly', 'loxes', 'loyal',
  'luaus', 'lubed', 'lubes', 'lucid', 'lucks', 'lucky', 'lucre', 'ludes', 'ludic', 'luffa',
  'lulls', 'lumen', 'lumps', 'lumpy', 'lunar', 'lunch', 'lunge', 'lungs', 'lurch', 'lured',
  'lures', 'lurks', 'lusts', 'lusty', 'luted', 'lutes', 'lying', 'lymph', 'lynch', 'lyres',
  'lyric', 'lysed', 'lyses', 'maced', 'maces', 'macho', 'macro', 'madam', 'madly', 'mafia',
  'magic', 'magma', 'magna', 'maids', 'mails', 'maims', 'mains', 'major', 'maker', 'makes',
  'males', 'malls', 'malts', 'mamas', 'mambo', 'mamma', 'mammy', 'mange', 'mango', 'mangy',
  'mania', 'manic', 'manly', 'manor', 'maple', 'march', 'mares', 'maria', 'marks', 'marry',
  'marsh', 'marts', 'massy', 'match', 'mated', 'mater', 'mates', 'maths', 'matte', 'mauls',
  'mauve', 'maxed', 'maxes', 'maybe', 'mayor', 'mazed', 'mazer', 'mazes', 'meads', 'meals',
  'mealy', 'means', 'meant', 'meats', 'meaty', 'mecca', 'medal', 'media', 'medic', 'meek',
  'meets', 'melds', 'melon', 'melts', 'memos', 'mends', 'menus', 'mercy', 'merit', 'merry',
  'meshy', 'messy', 'metal', 'meted', 'meter', 'metes', 'metro', 'mewed', 'mezzo', 'micro',
  'midst', 'miffs', 'might', 'miked', 'mikes', 'milks', 'milky', 'mills', 'milts', 'mimed',
  'mimes', 'mince', 'mincy', 'minds', 'mined', 'miner', 'mines', 'mingy', 'minim', 'minks',
  'minor', 'mints', 'minty', 'minus', 'mired', 'mires', 'mirth', 'misdo', 'miser', 'mists',
  'misty', 'miter', 'mitts', 'mixed', 'mixer', 'mixes', 'moats', 'mocha', 'modal', 'model',
  'modem', 'modes', 'mogul', 'moist', 'molar', 'molds', 'moldy', 'moles', 'molls', 'molts',
  'mommy', 'monad', 'mondo', 'money', 'monks', 'month', 'moods', 'moody', 'moons', 'moony',
  'moors', 'moose', 'moped', 'mopes', 'mopey', 'moral', 'moras', 'morel', 'mores', 'morns',
  'moron', 'morse', 'morts', 'mosey', 'mossy', 'motel', 'moths', 'motif', 'motor', 'motto',
  'mould', 'mound', 'mount', 'mourn', 'mouse', 'mousy', 'mouth', 'moved', 'mover', 'moves',
  'movie', 'mowed', 'mower', 'moxie', 'mucus', 'muddy', 'muffs', 'muggs', 'muggy', 'mulch',
  'mules', 'mulls', 'mumbo', 'mummy', 'mumps', 'munch', 'mungs', 'mural', 'murks', 'murky',
  'mushy', 'music', 'musky', 'musty', 'muted', 'mutes', 'mutts', 'muzak', 'mynah', 'mynas',
  'myrrh', 'myths', 'nabob', 'nacho', 'nacre', 'nadir', 'nails', 'naive', 'naked', 'named',
  'namer', 'names', 'nanny', 'naped', 'napes', 'nappy', 'narcs', 'nards', 'nares', 'narks',
  'nasty', 'natal', 'natch', 'nates', 'natty', 'naval', 'navel', 'naves', 'nazis', 'neals',
  'nears', 'neath', 'necks', 'needs', 'needy', 'neigh', 'nelly', 'neons', 'nerds', 'nerdy',
  'nerve', 'nests', 'netty', 'neume', 'never', 'newer', 'newly', 'newsy', 'newts', 'nexus',
  'nicer', 'niche', 'nicks', 'niece', 'nifty', 'night', 'nihil', 'nills', 'ninja', 'ninny',
  'ninth', 'nippy', 'nitro', 'nitty', 'nixed', 'nixes', 'nobby', 'noble', 'nobly', 'nocks',
  'nodal', 'nodes', 'nodus', 'noels', 'noise', 'noisy', 'nomad', 'nomes', 'nonce', 'nones',
  'nooks', 'noons', 'noose', 'norms', 'north', 'nosed', 'noses', 'nosey', 'notch', 'noted',
  'notes', 'notum', 'noun', 'novel', 'nowed', 'nowts', 'nubby', 'nubia', 'nucha', 'nuder',
  'nudes', 'nudge', 'nudie', 'nuked', 'nukes', 'nulls', 'numbs', 'nurse', 'nutty', 'nylon',
  'nymph', 'oaked', 'oaken', 'oared', 'oases', 'oasis', 'oaten', 'oater', 'oaths', 'oaves',
  'obeli', 'obese', 'obeys', 'obits', 'oboes', 'occur', 'ocean', 'ocher', 'ochre', 'octad',
  'octal', 'octet', 'oculi', 'oddly', 'odeum', 'odors', 'odour', 'offal', 'offed', 'offer',
  'often', 'ogees', 'ogham', 'ogive', 'ogled', 'ogler', 'ogles', 'ogres', 'ohias', 'ohing',
  'oiled', 'oiler', 'oinks', 'okays', 'olden', 'older', 'oldie', 'oleic', 'oleos', 'olive',
  'ollas', 'omega', 'omens', 'omits', 'oncet', 'onion', 'onset', 'oohed', 'oomph', 'ooped',
  'oozed', 'oozes', 'opahs', 'opals', 'opens', 'opera', 'opine', 'opium', 'opsin', 'opted',
  'opus', 'orach', 'orals', 'orang', 'orate', 'orbit', 'order', 'ordos', 'organ', 'orgma',
  'oriel', 'ormer', 'orris', 'osier', 'other', 'otter', 'ought', 'ounce', 'ousel', 'ousts',
  'outdo', 'outer', 'outgo', 'ovary', 'ovate', 'ovens', 'overs', 'overt', 'ovine', 'ovoid',
  'ovule', 'owing', 'owlet', 'owned', 'owner', 'oxbow', 'oxboy', 'oxeye', 'oxide', 'oxids',
  'oxime', 'oxims', 'oxlip', 'oyers', 'ozone', 'paced', 'pacer', 'paces', 'pacey', 'packs',
  'pacts', 'paddy', 'padre', 'pagan', 'paged', 'pager', 'pages', 'pails', 'pains', 'paint',
  'pairs', 'paise', 'palace', 'palms', 'palmy', 'palsy', 'panda', 'panel', 'pangs', 'panic',
  'pansy', 'panty', 'papas', 'paper', 'pappi', 'pappy', 'pards', 'pared', 'pares', 'pargo',
  'paris', 'parks', 'parry', 'parse', 'parts', 'party', 'pasha', 'pasta', 'paste', 'pasts',
  'pasty', 'patch', 'pated', 'paten', 'pater', 'pates', 'paths', 'patio', 'patsy', 'patty',
  'pause', 'paved', 'paver', 'paves', 'pawls', 'pawns', 'payed', 'payee', 'payer', 'peace',
  'peach', 'peaks', 'peaky', 'peals', 'peans', 'pearl', 'pears', 'pease', 'peats', 'peaty',
  'pecan', 'pecks', 'pedal', 'peeks', 'peels', 'peens', 'peers', 'peeve', 'pegma', 'pelfs',
  'pells', 'pelts', 'penal', 'pence', 'pends', 'penis', 'penny', 'peons', 'peony', 'peppy',
  'perch', 'perdu', 'perdy', 'peres', 'perfs', 'peril', 'perks', 'perky', 'perms', 'perps',
  'perry', 'perse', 'pervo', 'pervs', 'pests', 'petal', 'peter', 'petit', 'petre', 'petty',
  'phase', 'phial', 'phlox', 'phone', 'phony', 'photo', 'phyla', 'piano', 'pians', 'pibal',
  'pical', 'picas', 'picks', 'picky', 'picot', 'piece', 'piety', 'piggy', 'piker', 'pikes',
  'pikul', 'pilaf', 'piled', 'piles', 'pills', 'pilot', 'pimas', 'pimps', 'pinch', 'pined',
  'pines', 'pings', 'pinko', 'pinks', 'pinky', 'pinna', 'pinny', 'pinot', 'pinta', 'pinto',
  'pions', 'pious', 'pipal', 'piped', 'piper', 'pipes', 'pipet', 'pipit', 'pique', 'pirog',
  'pitch', 'piths', 'pithy', 'piton', 'pitta', 'pivot', 'pixel', 'pixie', 'pizza', 'place',
  'plage', 'plaid', 'plain', 'plait', 'plane', 'plank', 'plans', 'plant', 'plash', 'plate',
  'plats', 'platy', 'plays', 'plaza', 'plead', 'pleas', 'pleat', 'plebs', 'plied', 'plier',
  'plies', 'plink', 'plods', 'plonk', 'plops', 'plots', 'plows', 'ploys', 'pluck', 'plugs',
  'plumb', 'plume', 'plump', 'plums', 'plumy', 'plunk', 'plush', 'pluto', 'plyer', 'poach',
  'pocks', 'podgy', 'poems', 'poets', 'pogey', 'poind', 'point', 'poise', 'poked', 'poker',
  'pokes', 'pokey', 'polar', 'poled', 'poles', 'polio', 'polka', 'polls', 'polos', 'polyp',
  'pomps', 'ponds', 'pongy', 'pooch', 'poods', 'poofs', 'poofy', 'poohs', 'pools', 'poops',
  'poort', 'poove', 'popes', 'poppa', 'poppy', 'popsy', 'porch', 'pored', 'pores', 'porgy',
  'porks', 'porky', 'porno', 'porns', 'ports', 'posed', 'poser', 'poses', 'posit', 'posse',
  'posts', 'potsy', 'pound', 'poufs', 'poult', 'pound', 'pours', 'pouts', 'power', 'poxed',
  'poxes', 'praam', 'prads', 'prahu', 'prams', 'prang', 'prank', 'praos', 'prase', 'prate',
  'prats', 'praus', 'prays', 'preach', 'preen', 'preps', 'press', 'prexy', 'preys', 'price',
  'prick', 'pride', 'pried', 'prier', 'pries', 'prigs', 'prime', 'primo', 'primp', 'prims',
  'print', 'prior', 'prise', 'privy', 'prize', 'proas', 'probe', 'prods', 'proem', 'profs',
  'progs', 'prom', 'prone', 'prong', 'proof', 'props', 'prose', 'prost', 'prosy', 'proud',
  'prove', 'prowl', 'prows', 'proxy', 'prude', 'prune', 'pryse', 'psalm', 'pseud', 'psych',
  'pubes', 'pubic', 'pubis', 'pucks', 'pudge', 'pudgy', 'puffs', 'puffy', 'pujas', 'puked',
  'pukes', 'pukka', 'pulls', 'pulps', 'pulpy', 'pulse', 'pumas', 'pumps', 'punch', 'pungs',
  'punks', 'punky', 'punny', 'punts', 'pupas', 'pupil', 'puppy', 'pupus', 'purda', 'purge',
  'purls', 'purrs', 'purse', 'pursy', 'pushy', 'pussy', 'puton', 'putts', 'putty', 'pyins',
  'pylon', 'pyoid', 'pyran', 'pyres', 'pyric', 'pyros', 'pyxes', 'pyxis', 'qajaq', 'qapik',
  'qats', 'qawwals', 'qawwali', 'qawwal', 'qawwals', 'qidars', 'qigongs', 'qindar', 'qintars',
  'qiviut', 'qophs', 'qormas', 'quads', 'quaff', 'quags', 'quail', 'quake', 'quaky', 'quale',
  'qualm', 'quark', 'quart', 'quasi', 'quass', 'quays', 'queen', 'queer', 'quell', 'query',
  'quest', 'queue', 'quick', 'quiet', 'quiff', 'quill', 'quilt', 'quins', 'quips', 'quire',
  'quirk', 'quite', 'quits', 'quods', 'quoit', 'quota', 'quote', 'quoth', 'qursh', 'rabat',
  'rabbi', 'rabid', 'raced', 'racer', 'races', 'racks', 'radar', 'radii', 'radio', 'radix',
  'radon', 'raffs', 'rafts', 'raged', 'rages', 'ragis', 'raias', 'raids', 'rails', 'rains',
  'rainy', 'raise', 'raita', 'rajah', 'rajas', 'raked', 'raker', 'rakes', 'rales', 'rally',
  'ramps', 'ramus', 'ranch', 'rands', 'randy', 'ranee', 'range', 'rangy', 'ranks', 'rants',
  'raped', 'raper', 'rapes', 'rapid', 'rared', 'rarer', 'rares', 'rasae', 'rased', 'raser',
  'rases', 'rasps', 'raspy', 'rated', 'rater', 'rates', 'rathe', 'ratio', 'ratty', 'raved',
  'ravel', 'raven', 'raver', 'raves', 'rawer', 'rawly', 'rayed', 'rayon', 'razed', 'razer',
  'razes', 'razor', 'reach', 'react', 'reads', 'ready', 'realm', 'reams', 'reaps', 'rears',
  'rebar', 'rebel', 'rebus', 'rebut', 'recap', 'recce', 'recks', 'recon', 'recta', 'recto',
  'recur', 'redds', 'reded', 'redes', 'redia', 'reeds', 'reedy', 'reefs', 'reefy', 'reeks',
  'reeky', 'reels', 'reeve', 'refed', 'refer', 'refit', 'refix', 'regal', 'reges', 'rehab',
  'rehem', 'reign', 'reiki', 'reins', 'reive', 'rejig', 'relax', 'relay', 'relet', 'relic',
  'relit', 'remap', 'remex', 'remit', 'remix', 'renal', 'rends', 'renew', 'rente', 'rents',
  'repay', 'repel', 'reply', 'repos', 'repot', 'repps', 'repro', 'reset', 'resin', 'rests',
  'retch', 'retag', 'retie', 'retro', 'retry', 'reuse', 'revel', 'revet', 'revs', 'rewax',
  'rewin', 'rewon', 'rheas', 'rheme', 'rheum', 'rhino', 'rhyme', 'rhynd', 'rials', 'riata',
  'ribbs', 'riced', 'ricer', 'rices', 'ricin', 'ricks', 'rider', 'rides', 'ridge', 'ridgy',
  'rifer', 'riffs', 'rifle', 'rifts', 'right', 'rigid', 'rigor', 'riled', 'riles', 'rille',
  'rills', 'rimae', 'rimed', 'rimer', 'rimes', 'rinds', 'rings', 'rinks', 'rinse', 'riots',
  'riped', 'ripen', 'riper', 'ripes', 'risen', 'riser', 'rises', 'risks', 'risky', 'risus',
  'rites', 'ritzy', 'rival', 'rived', 'rivel', 'riven', 'river', 'rives', 'rivet', 'roach',
  'roads', 'roams', 'roans', 'roar', 'roars', 'roast', 'robed', 'robes', 'robin', 'robot',
  'rocks', 'rocky', 'rodeo', 'roger', 'roles', 'rolls', 'romal', 'roman', 'romps', 'ronco',
  'rondo', 'roods', 'roofs', 'rooks', 'rooms', 'roomy', 'roose', 'roost', 'roots', 'rooty',
  'roped', 'roper', 'ropes', 'ropey', 'roque', 'rosed', 'roses', 'roset', 'rosts', 'rotal',
  'rotas', 'rotch', 'rotes', 'rotis', 'rotls', 'rotor', 'rotos', 'rotte', 'rouen', 'rouge',
  'rough', 'roule', 'round', 'roups', 'roupy', 'rouse', 'roust', 'route', 'routh', 'routs',
  'roved', 'roven', 'rover', 'roves', 'rowan', 'rowdy', 'rowed', 'rowel', 'rowen', 'rower',
  'rowth', 'royal', 'royst', 'rozet', 'rubai', 'rubby', 'rubel', 'rubes', 'ruble', 'rubus',
  'ruche', 'rucks', 'rudds', 'ruddy', 'ruder', 'ruers', 'ruffs', 'rugae', 'rugby', 'ruins',
  'rukhs', 'ruled', 'ruler', 'rules', 'rumba', 'rumen', 'rumes', 'rumly', 'rummy', 'rumor',
  'rumps', 'runed', 'runes', 'rungs', 'runic', 'runny', 'runts', 'runty', 'rupee', 'rural',
  'rusas', 'rush', 'rushy', 'rusks', 'russe', 'rusts', 'rusty', 'rutas', 'ruths', 'rutty',
  'ryked', 'rykes', 'ryots', 'saags', 'sabal', 'sabed', 'saber', 'sabes', 'sabir', 'sable',
  'sabot', 'sabra', 'sabre', 'sac', 'sacks', 'sadhu', 'sadly', 'safer', 'safes', 'sagas',
  'sager', 'sages', 'saggy', 'sagos', 'sagum', 'saheb', 'sahib', 'saice', 'saids', 'saiga',
  'sails', 'sains', 'saint', 'saith', 'sajou', 'sakai', 'saker', 'sakes', 'sakis', 'salad',
  'salal', 'salep', 'sales', 'salic', 'sally', 'salmi', 'salon', 'salp', 'salpa', 'salps',
  'salsa', 'salts', 'salty', 'salue', 'salut', 'salve', 'salvo', 'sambo', 'samek', 'sames',
  'samfu', 'samhi', 'sampi', 'samps', 'sands', 'sandy', 'saned', 'saner', 'sanes', 'sanga',
  'sangh', 'sango', 'sangs', 'sanko', 'sansa', 'santo', 'sants', 'saped', 'saper', 'sapes',
  'sapid', 'sapor', 'sappy', 'saran', 'sard', 'sards', 'sarge', 'sargo', 'sarin', 'saris',
  'sarks', 'sarky', 'sarod', 'saros', 'sashay', 'sasin', 'sassy', 'satai', 'satan', 'satem',
  'sates', 'satin', 'satis', 'satyr', 'sauch', 'sauce', 'sauch', 'saucy', 'sauds', 'sauld',
  'sault', 'sauna', 'saunt', 'saury', 'saute', 'saved', 'saver', 'saves', 'savin', 'savor',
  'savoy', 'savvy', 'sawed', 'sawer', 'sawed', 'saxes', 'sayed', 'sayer', 'sayid', 'scabs',
  'scads', 'scaff', 'scald', 'scale', 'scall', 'scalp', 'scaly', 'scamp', 'scams', 'scand',
  'scans', 'scant', 'scare', 'scarf', 'scarp', 'scars', 'scary', 'scats', 'scatt', 'scaup',
  'scena', 'scend', 'scene', 'scent', 'schav', 'schmo', 'schul', 'scilla', 'scion', 'sclag',
  'scoff', 'scold', 'scone', 'scoop', 'scoot', 'scope', 'scops', 'score', 'scorn', 'scots',
  'scour', 'scout', 'scowl', 'scows', 'scrab', 'scrag', 'scram', 'scrap', 'scrat', 'scraw',
  'screak', 'scree', 'screw', 'scrim', 'scrip', 'scrub', 'scuds', 'scuff', 'sculk', 'scull',
  'sculp', 'scums', 'scups', 'scurf', 'scuta', 'scute', 'scuts', 'scuzz', 'seals', 'seams',
  'seamy', 'seans', 'sears', 'seats', 'sebum', 'secco', 'sects', 'sedan', 'seder', 'sedes',
  'sedge', 'sedgy', 'sedum', 'seeds', 'seedy', 'seeks', 'seems', 'seeps', 'seepy', 'segal',
  'segni', 'segno', 'segos', 'segue', 'seifs', 'seils', 'seine', 'seise', 'seism', 'seize',
  'selah', 'selas', 'seldom', 'seles', 'sella', 'sells', 'selva', 'semen', 'semes', 'semic',
  'semis', 'senas', 'sends', 'senes', 'sengi', 'senna', 'senor', 'sensa', 'sense', 'sente',
  'senti', 'sents', 'sepal', 'sepia', 'sepic', 'sepoy', 'septa', 'seral', 'sered', 'serer',
  'seres', 'serfs', 'serge', 'serif', 'serin', 'serow', 'serra', 'serre', 'serum', 'serve',
  'servo', 'sesar', 'setal', 'seton', 'setae', 'setup', 'seven', 'sever', 'sewed', 'sewer',
  'sewn', 'sexed', 'sexes', 'sexto', 'sexts', 'shack', 'shade', 'shads', 'shady', 'shaft',
  'shags', 'shahs', 'shake', 'shako', 'shaks', 'shaky', 'shale', 'shall', 'shalt', 'shame',
  'shams', 'shank', 'shans', 'shape', 'shaps', 'shard', 'share', 'shark', 'sharn', 'sharp',
  'shash', 'shaul', 'shave', 'shawl', 'shaws', 'shays', 'shchi', 'sheaf', 'sheal', 'shear',
  'sheas', 'sheds', 'sheen', 'sheep', 'sheer', 'sheet', 'shelf', 'shell', 'shend', 'shent',
  'sheol', 'sherd', 'shere', 'shero', 'shers', 'shew', 'shews', 'shiai', 'shick', 'shied',
  'shiel', 'shier', 'shies', 'shift', 'shill', 'shily', 'shims', 'shine', 'shins', 'shiny',
  'ships', 'shire', 'shirk', 'shirr', 'shirt', 'shist', 'shits', 'shiva', 'shive', 'shivs',
  'shlep', 'shlub', 'shoal', 'shoat', 'shock', 'shoed', 'shoer', 'shoes', 'shogs', 'shoji',
  'shojo', 'shone', 'shook', 'shool', 'shoon', 'shoop', 'shoot', 'shops', 'shore', 'shorl',
  'shorn', 'short', 'shote', 'shots', 'shott', 'shout', 'shove', 'shown', 'shows', 'showy',
  'shred', 'shrew', 'shris', 'shrub', 'shrug', 'shtik', 'shuck', 'shuds', 'shuls', 'shuns',
  'shunt', 'shura', 'shush', 'shute', 'shuts', 'shwas', 'shyer', 'shyly', 'sials', 'sibbs',
  'sibyl', 'sices', 'sicko', 'sicks', 'sicky', 'sided', 'sider', 'sides', 'sidhe', 'sidle',
  'siege', 'sient', 'sieve', 'sifts', 'sighs', 'sight', 'sigil', 'sigma', 'signs', 'sigul',
  'silks', 'silky', 'sills', 'silly', 'silos', 'silts', 'silty', 'silva', 'simar', 'simas',
  'simba', 'simes', 'simps', 'since', 'sinew', 'singe', 'sings', 'sinks', 'sinus', 'siped',
  'sipes', 'sippy', 'sired', 'siren', 'sires', 'sirup', 'sisal', 'sises', 'sissy', 'sitar',
  'sited', 'sites', 'situp', 'situs', 'siver', 'sixes', 'sixmo', 'sixte', 'sixth', 'sixty',
  'sizar', 'sized', 'sizer', 'sizes', 'skags', 'skald', 'skank', 'skarf', 'skarn', 'skart',
  'skate', 'skats', 'skaws', 'skean', 'skear', 'skeds', 'skeed', 'skees', 'skeet', 'skeg',
  'skein', 'skell', 'skelm', 'skelp', 'skene', 'skens', 'skeos', 'skeps', 'skers', 'skews',
  'skids', 'skied', 'skier', 'skies', 'skiff', 'skift', 'skiis', 'skill', 'skimo', 'skimp',
  'skims', 'skink', 'skins', 'skint', 'skios', 'skips', 'skirl', 'skirr', 'skirt', 'skite',
  'skits', 'skive', 'skoal', 'skoff', 'skook', 'skort', 'skosh', 'skuas', 'skulk', 'skull',
  'skunk', 'skyed', 'skyey', 'slabs', 'slack', 'slags', 'slain', 'slake', 'slams', 'slang',
  'slank', 'slant', 'slaps', 'slash', 'slate', 'slats', 'slaty', 'slave', 'slaws', 'slays',
  'sled', 'sleds', 'sleek', 'sleep', 'sleet', 'slept', 'slews', 'slice', 'slick', 'slide',
  'slier', 'slily', 'slime', 'slims', 'slimy', 'sling', 'slink', 'slipe', 'slips', 'slish',
  'slits', 'slive', 'slobs', 'sloes', 'slogs', 'sloid', 'slojd', 'sloka', 'slomo', 'sloop',
  'slope', 'slops', 'slosh', 'sloth', 'slots', 'slows', 'sloyd', 'slubs', 'slude', 'slued',
  'slues', 'sluff', 'slugs', 'slump',
  // ... Continue adding more words as needed
  'abaca', 'abacus', 'abbey', 'abc', 'abled', 'abode', 'abort', 'about', 'above', 'abuse',
  'abyss', 'acute', 'admit', 'adopt', 'adult', 'after', 'again', 'agent', 'agree', 'ahead'
]

export async function seedDatabase() {
  console.log('Starting database seed...')
  
  try {
    // Seed secret words
    console.log('Seeding secret words...')
    for (const word of SECRET_WORDS) {
      await prisma.secretWord.upsert({
        where: { word },
        create: { word },
        update: {}
      })
    }
    console.log(`Seeded ${SECRET_WORDS.length} secret words`)
    
    // Seed dictionary words
    console.log('Seeding dictionary words...')
    for (const word of DICTIONARY_WORDS) {
      await prisma.dictionary.upsert({
        where: { word },
        create: { word },
        update: {}
      })
    }
    console.log(`Seeded ${DICTIONARY_WORDS.length} dictionary words`)
    
    console.log('Database seed completed successfully!')
  } catch (error) {
    console.error('Error seeding database:', error)
    throw error
  }
}